### ISSUE TITLE
can't log with steam account in the new version

### ISSUE THREAD

**Issue by fanyo11** [BetterOtherRoles/BetterOtherRoles#3]
**Describe the bug**
when you start the game with the new version, the game don't succed to log me with my steam account. like i can't log to my steam account, i can't join online room

**To Reproduce**
start the game

**Expected behavior**
well I can't log and I'm not the only one who can't log, some friend test the new version and their can't log to their account

**Screenshots**
![image](https://github.com/BetterOtherRoles/BetterOtherRoles/assets/142608460/21ea7d4c-88a5-4844-93b8-79ea9ce8b579)

**System (please complete the following information):**
 - OS: Windows 10
 - Among Us Version  v2023.7.12s
 - BetterOtherRoles Version  v1.4.0]

**Additional context**

**Comment by Thiladon** [comment]
Hi there,

First of all, u can disable the console in bepinex/config/BepInEx.cfg, search for the [Logging.Console] part and set it to Enabled = false and save the file.

Then for ur problem, look for the steam_appid.txt file that should be in the root folder, I'm guessing there is none for u and that what cause the problem.

Just make one and filled it with "945360" and save.
Should fix the problem :)

**Comment by fanyo11** [comment]
yes thank, steam_appid.txt was missing, it seem that it get remove from the folder

**Comment by Thiladon** [comment]
Yeah, we (mainly 99% EnoPM ATM) are redoing all of the stuff to get rid of some previous bug, it's a matter of time before everything is well setup.

I'll put this as fixed, enjoy your experience and future games !
