### ISSUE TITLE
[Bug Report] Custom servers are not installed due to missing config file

### ISSUE THREAD

**Issue by miniduikboot** [BetterOtherRoles/BetterOtherRoles#4]
**Describe the bug**
By default Mini.RegionInstall does not install any servers, if you wish to install custom servers you need to add a configuration file in your release zip

**To Reproduce**
1. Go to `%APPDATA%\..\LocalLow\Innersloth\Among Us` and remove the file regionInfo.json (this simulates a fresh install)
2. Install Better Other Roles
3. Go to the online multiplayer menu and click the globe
4. See that no custom servers were installed

**Expected behavior**
Expected to see custom servers installed

**System (please complete the following information):**
 - I determined the existence of this issue by looking into the mod zip
 - BetterOtherRoles Version 1.4.0 (1.2.0 not affected, it does have an at.duikbo.regioninstall.cfg configuration file configured with the modded servers)

**Additional context**
Furthermore I see that you didn't change the Discord link in the readme of this repository: if you have your own discord server, you may want to change it to your own. The TOR server help chat does not support forks.

**Comment by Thiladon** [comment]
Hello,

First of all, thanx, we will look into it.

As for the discord, we don't have one released yet but we will change the readme in the day so TOR will have no more problems :)

**Comment by miniduikboot** [comment]
Feel free to ship the modded servers, they're open for all client mods to use. Let me know if you need help with Mini.RegionInstall
